# Generated by Django 3.2.15 on 2022-09-18 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0004_posttutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttutorial',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posttutorial',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
