# Generated by Django 3.2.15 on 2022-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0005_auto_20220918_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
