# Generated by Django 3.2.15 on 2022-09-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0006_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
