# Generated by Django 3.2.15 on 2022-09-19 12:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skateapp', '0007_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
