# Generated by Django 3.2.15 on 2022-09-19 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skateapp', '0010_profile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
